# 服务端口号
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    context-path: /graduation


spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.66.245:43306/graduationproject?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  application:
    name: GraduationProject

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

  mvc:
    pathmatch:
      # Knife4j 2.x 配置策略
      matching-strategy: ant_path_matcher


mybatis:
  mapper-locations: classpath*:mapper/*.xml